class MessageComponent:
    see_shop = '[دیدن فروشگاه]'
    shop_name = 'نام فروشگاه : '
    username = 'نام کاربری : '
    phoneNumber = 'شماره تماس : '
    description = 'توضیحات : '
    startTime = 'ساعت شروع به کار : '
    endTime = 'ساعت پایان کار : '
    stars = 'امتیاز : '
    title = 'عنوان ؛ '
    text = 'توضیحات : '
    price = 'قیمت : '
    discount = 'تخفیف : '
    see_product = '[دیدن محصول]'
